version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run linting
          command: npm run lint
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Test build output
          command: |
            if [ ! -d "dist" ]; then
              echo "Build failed: dist directory not found"
              exit 1
            fi
            echo "Build successful: dist directory created"
      - persist_to_workspace:
          root: .
          paths:
            - dist/
            - node_modules/

  deploy:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install gh-pages
          command: npm install -g gh-pages
      - run:
          name: Deploy to GitHub Pages
          command: |
            if [ "${CIRCLE_BRANCH}" = "main" ]; then
              echo "Deploying to GitHub Pages..."
              gh-pages -d dist --dotfiles
            else
              echo "Skipping deployment for branch: ${CIRCLE_BRANCH}"
            fi
          environment:
            GITHUB_TOKEN: ${GITHUB_TOKEN}

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
