version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run linting
          command: npm run lint
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Test build output
          command: |
            if [ ! -d "dist" ]; then
              echo "Build failed: dist directory not found"
              exit 1
            fi
            echo "Build successful: dist directory created"
      - run:
          name: Store build artifacts
          command: |
            echo "Build artifacts stored in dist/ directory"
            ls -la dist/
      - persist_to_workspace:
          root: .
          paths:
            - dist/

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
